import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PostCard, PostWidget, Categories } from '../components'
import { getPosts } from '../services'



export default function Home({posts }) {
  console.log(posts);
  return (
    <div className="container px-10 mx-auto mb-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="col-span-1 lg:col-span-8 ">
          {
            posts.map( (post, index ) => 
            {
             return <PostCard key={post.title} post={post.node} > </PostCard>
            
            })
          }
        </div>

        <div className="lg:col-span-4 col-span-1"> 
        <div className="lg:sticky relative top-8">
          <PostWidget></PostWidget>
          <Categories></Categories>
        </div>
         
        </div>
        </div>
    </div>
  )
}

export async function getStaticProps(){
  const posts = await(getPosts()) || [];
  console.log(posts)
  return {
    props :{posts}
  }
}
